
spring:
  application:
    name: Cohort-Management-Service
  profiles:
    active: ${profile:prod}
server:
  port: ${cohort-management-port:9000}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

