spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cohorts-management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
services:
  specialization:
    base-url: ${specialization_service:lb://specialization-service/api/v1}
  user-profile:
    base-url: ${trainee_service:lb://user-profile-service/api/v1}
  cohort-management:
    overlapping-period: ${overlapping_period:0}
resilience4j:
  circuitbreaker:
    instances:
      ExternalServiceBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
server:
  port: 8081
  forward-headers-strategy: framework
